name: C++ CI

on:
  push:
    branches:
      - master
  pull_request: # Optionally run on pull requests
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Install dependencies
        run: sudo apt install qtbase5-dev

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
          
      - name: Run the program
        run: |
          ./build/GameOfLife
