name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y cmake make g++

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      #- name: Run tests
       # run: ./build/tests
